services:
  db:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pw

  api:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  db_data: {}
